version: '2.4'
services:
  app:
    image: ghcr.io/docbrown101/qr-code-generator:main
    container_name: qr-code-generator
    restart: on-failure:1
    ports:
      - 80:80
    user: 1001:1001
    security_opt:
      - apparmor:docker-default
      - no-new-privileges
    cpu_shares: 10
    pids_limit: 10
    mem_limit: 100m
    read_only: true
    tmpfs:
      - /var/run:mode=770,size=512K,uid=1001,gid=1001
      - /var/cache/nginx:mode=770,size=512K,uid=1001,gid=1001
